apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mrc-full-test
  labels:
    # any Pods with matching labels are included in this Daemon Set
    app: kubernetes-series
    tier: monitor
spec:
  selector:
    # Pods will match with the following labels
    matchLabels:
      name: mrc-full-test
  template:
    metadata:
      labels:
        name: mrc-full-test
    spec:
      containers:
      - name: mrc-full-test
        image: contoso.azurecr.io/contoso/mrc-full-gpu:latest
        ports:
        - containerPort: 80
        command: ["sleep", "infinity"]
        resources:
          limits:
           nvidia.com/gpu: 1
--- 
apiVersion: v1
kind: Service
metadata:
  name: mrc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    name: mrc-full-test
